# @package _global_

# few-shot eval
eval_mode: "few_shot"

# train_n_way: 5
n_way: 5
n_shot: 5
n_query: 15
print_val: false

data:
  n_way: ${n_way}
  n_shot: ${n_shot}
  n_query: ${n_query}

  num_episodes: 300
  val_aug: "few_shot_test"

trainer:
  replace_sampler_ddp: false
