# @package _global_
system_name: few_shot

# default logistic regression
defaults:
  - _self_
  - /scheduler: none
  - /callbacks: none
  # - /eval: few_shot
  # - /eval/fine_tune: LR
  - /fs_optimizer@eval.fine_tune.post_train.optimizer
  - /fs_optimizer@eval.fine_tune.pre_train.optimizer

support_batch_size: 5
support_aug: "few_shot_query"
support_repeat: 1

query_aug: null

test: true
load_base: true
eval_mode: "few_shot"

# train_n_way: 5
n_way: 5
n_shot: 5
n_query: 15
print_val: true

data:
  n_way: ${n_way}
  n_shot: ${n_shot}
  n_query: ${n_query}

  num_episodes: 300
  val_aug: "few_shot_test"

  val_dataset: null
  dataset: null
  test_dataset: EuroSAT_test

launcher:
  time: "6"

trainer:
  checkpoint_callback: False
  replace_sampler_ddp: false

eval:
  fine_tune:
    name: "LR"
    use_norm: false

    freeze_bn: false
    last_k: null

    post_train:
      reset_head: true
      freeze_backbone: true
      use_norm: false
