# @package _global_

model_name: "tsne"

data:
  dataset: EuroSAT_test
  test_dataset: null
  val_dataset: null
  num_classes: 100
  train_aug: false
  val_aug: false

  batch_size: 128

projection: null # tsne, PCA

test: true
diable_logfile: true
load_base: true
disable_validation: true

out_path: "figs/clustering"

trainer:
  gpus: 1
  progress_bar_refresh_rate: 2
