# @package _global_

callbacks:
  model_checkpoint:
    _target_: callbacks.custom_callbacks.CheckpointCallback
    monitor: "acc_mean" # name of the logged metric which determines when model is improving
    save_top_k: 1 # save k best models (determined by above metric)
    save_last: True # additionaly always save model from last epoch
    mode: "max" # can be "max" or "min"
    filename: "{epoch:03d}"
    dirpath: ${trainer.weights_save_path}
    verbose: true
    save_every_n_epoch: null
